### ISSUE TITLE
Some features from Xplotter v.1.1 have been lost on the way to v.1.21

### ISSUE THREAD

**Issue by JohnnyFFM** [JohnnyFFM/XPlotter#1]
Seems like Blago lost the code for v.1.1, so I had to start from v.1.0. This means that some new feature of v.1.1 have been lost. So far I've only found two differences between v.1.0 and v.1.1:
(1) AVX2 was not building properly in v.1.0 
(2) Stats when plotting look slightly different (percentage progress vs. absolute progress in nonces, added MB/s stats for the write)

I've fixed (1) for v.1.21, but (2) is still outstanding (not a big thing anyway). If there is anything else missing please let me know. 

Johnny

**Comment by Blagodarenko** [comment]
Hi! Thank you for enhancement the project!
At now i have not the time for it.
I tried to restore v1.1, but need to recheck it, sources in additions.
[XPlotter1.1.zip](https://github.com/JohnnyFFM/XPlotter/files/2080702/XPlotter1.1.zip)

**Comment by JohnnyFFM** [comment]
Many thanks Blago, will have a look!

**Comment by Blagodarenko** [comment]
please, add optimizations, see "// optimization: avx1_mshabal_init(mx, 256)" and "// optimization: reduced 8064 assignments" -  10-15% faster

**Comment by ohager** [comment]
@Blagodarenko  HEUREKA! That's what I was looking for - the optimizations!

**Comment by JohnnyFFM** [comment]
I've just merged v.1.1 and created Xplotter v.1.3 with all the missing stuff added. Thanks @Blagodarenko ! 
@ohager : Agreed one of the two should be sufficient. Let's compare both again (features / output / speed) and then make a vote. Will have some free time after 502k for this 😃.
