### ISSUE TITLE
POC2 Plotting disabled?

### ISSUE THREAD

**Issue by Temido2222** [JohnnyFFM/XPlotter#2]
When plotting, XPlotter will say "POC2 Plotting disabled." at the start of plotting. How can I force POC2 plots?

**Comment by JohnnyFFM** [comment]
You would need to add the switch -poc2 to the command line.

**Comment by InjectedPie** [comment]
could you add the string to the default batchfile on the next release ?

what about the xplotter fork splotter https://github.com/Hypsy/SPlotter/tree/master/SPlotter its great for "cached plotting" in use with smr drives it also has some other stuff that i want to see here
